name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Download and build cURL
        shell: cmd
        run: build_win.bat
